import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" bg-[url(https://i.imgur.com/dXOYa9N.png/GK41rZ4.png)] min-h-screen bg-contain bg-fixed">
          {children}
        </main>
        <Script src="/liquid-glass.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
